vich_uploader:
    db_driver: orm

    mappings:
        wikiPB:
            uri_prefix: /images/wikiPB
            upload_destination: '%kernel.project_dir%/public/uploads/wikiTitlePictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer